# Generated by Django 5.2.5 on 2025-08-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_updated_at_alter_ticket_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menulevel2',
            unique_together={('parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menulevel3',
            unique_together={('parent', 'name')},
        ),
    ]
